export const nationalities = [
  { value: 'FRANCE', label: 'France' },
  { value: 'GERMANY', label: 'Allemagne' },
  { value: 'SPAIN', label: 'Espagne' },
  { value: 'ITALY', label: 'Italie' },
  { value: 'PORTUGAL', label: 'Portugal' },
  { value: 'BELGIUM', label: 'Belgique' },
  { value: 'SWITZERLAND', label: 'Suisse' },
  { value: 'LUXEMBOURG', label: 'Luxembourg' },
  { value: 'UNITED_KINGDOM', label: 'Royaume-Uni' },
  { value: 'NETHERLANDS', label: 'Pays-Bas' },
  { value: 'AUSTRIA', label: 'Autriche' },
  { value: 'DENMARK', label: 'Danemark' },
  { value: 'SWEDEN', label: 'Suède' },
  { value: 'NORWAY', label: 'Norvège' },
  { value: 'FINLAND', label: 'Finlande' },
  { value: 'GREECE', label: 'Grèce' },
  { value: 'IRELAND', label: 'Irlande' },
  { value: 'ICELAND', label: 'Islande' },
  { value: 'POLAND', label: 'Pologne' },
  { value: 'HUNGARY', label: 'Hongrie' },
  { value: 'CZECH_REPUBLIC', label: 'République Tchèque' },
  { value: 'SLOVAKIA', label: 'Slovaquie' },
  { value: 'SLOVENIA', label: 'Slovénie' },
  { value: 'CROATIA', label: 'Croatie' },
  { value: 'BULGARIA', label: 'Bulgarie' },
  { value: 'ROMANIA', label: 'Roumanie' },
  { value: 'LITHUANIA', label: 'Lituanie' },
  { value: 'LATVIA', label: 'Lettonie' },
  { value: 'ESTONIA', label: 'Estonie' },
];
